name: Docker Image CI
on: 
    push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nun-db:latest
    - name: Re-tag
      run: docker tag nun-db:latest mateusfreira/nun-db:latest
    - name: Publish
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}&&docker push mateusfreira/nun-db:latest

