name: Rust
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      if: ${{ !env.ACT }}
      run: cargo build --verbose
    - name: Start Minio
      if: ${{ !env.ACT }}
      run: docker compose up -d minio && sleep 5 && docker compose up minio-init
    - name: Run Unt tests
      env:
        TIME_TO_START: 1
        NUN_S3_KEY_ID: nun-db
        NUN_S3_SECRET_KEY: nun-db-something-more
        NUN_LOG_LEVEL: info
      run: cargo test --lib
    - name: Run integration tests
      env:
        TIME_TO_START: 1
      run: mkdir dbs&&cargo test --test '*' -- --test-threads=1 # threads=1 to avoid the problem with the in disk tests
